version: 2
updates:

  # Manage Github Actions versions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: "friday"
    labels:
      - "chore"
    open-pull-requests-limit: 10
